# The Trails of the South Mountain Reservation (SMR)

The [South Mountain Reservation](https://essexcountyparks.org/parks/south-mountain-reservation) is a 2112 acre park of Essex County New Jersey.

> South Mountain Reservation covers 2,112 acres in the central section of Essex County, extending through the municipalities of West Orange, Maplewood, and Millburn,  bordering South Orange, between the first and second ridges of the Watchung Mountain Range. The presence of the early Lenape Indians lingers in the name given to the Watchung—the "high hills."

>  The reservation has changed only slightly through the years. It's been preserved primarily in its wild state. Woodlands abound in a variety of hardwood trees, and tall hemlocks tower above streams, creeks and ponds. The west branch of the Rahway River flows through the valley. A reservoir and watershed owned by the City of Orange lies in the northern tract

> Largest of the Park System's reservations, it was built from land purchases begun in 1895—the first year of the Park Commission's life.  It took a decade to untangle the deeds and assemble all the lands at South Mountain.

> Before he delegated design of the Essex Parks to his stepson's firm, Frederick Law Olmsted visited the newly acquired reservation.  He regarded it as some of the most beautiful and promising terrain he had ever seen.  The design of South Mountain was finalized by the Olmsted Brothers in stages over the years.  A good deal of construction work--trails, foot bridges, shelters, etc.—was carried out by the Civilian Conservation Corps in the 1930's.

The [South Mountain Conservancy](https://www.somocon.org/) is a volunteer-driven, non profit:

> The South Mountain Conservancy serves as steward and advocate for the South Mountain Reservation.  We work to preserve, protect and restore its ecology, natural beauty, and infrastructure through our volunteer programs, promoting sustainable use, informing public policy and community engagement.




## Maps

A few maps of SMR are publicly available:

* 1902 Guide map of the South Mountain Reservation in Long Hill Township, Essex County, N.J. sponsored by the Essex County Park Commission. Surveyed under the direction of Howard J. Cole, Engineer in Chief and Gordon H. Taylor, Topographer. [Olmstead Brothers *design*](https://rucore.libraries.rutgers.edu/rutgers-lib/19844/)


* 1980s(?) (author and date unknown) [Essex County Map](https://essexcountyparks.org/_media/_data/EssexLocation/SMR-Trail-Map_legal.jpg)


* 2000s The SMC has released at least three version of its [trail map](https://www.somocon.org/product/smr-trail-map/), the last two produced by Susan Brand. These have been available for purchase and remain a source of revenue for the SMC. In addition, the map is available on both Androd and Apple through Avenza.
